### ISSUE TITLE
As a user I would like to do a small quiz to personalize the options supplied to me

### ISSUE THREAD

**Issue by Oliversw** [fac-15/snowflakes#12]
relates #9 
 
- [ ] Create and style the first quiz page
- [ ] Use this first page as a template to create the remaining 4 pages
- [ ] Each page contains at least two questions
- [ ] Each page contains breadcrumbs/a progress bar
- [ ] Each page has an effect on the final 3 suggested actions
- [ ] User can skip question
