### ISSUE TITLE
Stretch Goals

### ISSUE THREAD

**Issue by Oliversw** [fac-15/snowflakes#17]
- [ ] Send an HTML email with links to results and a link to app (to a friend)
- [ ] Be able to click on a category to see all of the results in that category
- [ ] Ability to pin/save actions that you like while you are exploring the different categories
