### ISSUE TITLE
As a user I would like to know some simple actions that I can take to get involved in making an impact against climate change (or other social issues)

### ISSUE THREAD

**Issue by Oliversw** [fac-15/snowflakes#9]
- [ ] When I start, I want to know what the goal of the app is
- [ ] When I start, I want to be shown instructions about how to navigate the app
- [ ] I would like to do a small quiz to personalize the options supplied to me
- [ ] I would like to be provided some simple actions that I can take to get involved/make a difference
- [ ] I would like the option to see more options of actions
- [ ] I would like the option to receive my suggested actions by email
- [ ] I would like the option to send the app to a friend
